version: "3.4"
services:
  riemann:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    command: "bin/riemann etc/riemann.config"
    volumes:
      - "./config/riemann.config:/riemann-0.3.5/etc/riemann.config"
    ports:
      - "5555:5555"
      - "4567:4567"
